/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/7.0.62 (1.7.2)
 * Generated at: 2015-11-30 01:25:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Userhomepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/userhomepagestyles.css", Long.valueOf(1448845560000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t   <!-- The Sale Notifier Splash Page\n");
      out.write("\t        Author: Michael Haight & Mohamed Saleh\n");
      out.write("\t        Data:   10/30/2015\n");
      out.write("\t   -->\n");
      out.write("\t   <meta charset=\"UTF-8\" />\n");
      out.write("\t   <title>Sale Notifier</title>\n");
      out.write("\t   <script src=\"modernizr-1.5.js\"></script>\n");
      out.write("<style>  ");
      out.write("/*\n");
      out.write("   Splash User Home page style sheet\n");
      out.write("   Author: Michael Haight & Mohamed Saleh\n");
      out.write("   Date:   10/31/2015\n");
      out.write("\n");
      out.write("   Filename: userhomepagestyles.css\n");
      out.write("   Supporting Files: none\n");
      out.write("\n");
      out.write("*/\n");
      out.write("\n");
      out.write("/* Section Styles */\n");
      out.write("\n");
      out.write("body {\n");
      out.write("\tmargin: 0px auto;\n");
      out.write("\tpadding: 0px;\n");
      out.write("\n");
      out.write("\twidth: 98%;\n");
      out.write("\tmax-width: 980px;\n");
      out.write("\tmin-width: 250px;\n");
      out.write("\tfont-family: Verdana, Geneva, sans-serif\n");
      out.write("}\n");
      out.write("\n");
      out.write("header {\n");
      out.write("\twidth: 100%;\n");
      out.write("\tmargin-top: 2em;\n");
      out.write("\ttext-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("section {\n");
      out.write("\twidth: 66%;\n");
      out.write("\tfloat: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Block Styles */\n");
      out.write("h1, h2, h3, h4, h5, h6 {\n");
      out.write("\tfont-family: Arial, Helvetica, sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header h1 {\n");
      out.write("   margin: 1em 0em 0em -20em;\n");
      out.write("   font-size: 2em;\n");
      out.write("}\n");
      out.write("\n");
      out.write("h2 {\n");
      out.write("   display: block;\n");
      out.write("   margin: 2em 10em 0em -5em;\n");
      out.write("   font-size: 1.5em;\n");
      out.write("   padding: 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("fieldset input {\n");
      out.write("   display: block;\n");
      out.write("   position: relative;\n");
      out.write("   float: left;\n");
      out.write("   margin: 0em 0em 0em 1em;\n");
      out.write("   height: 25px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#searchbar{\n");
      out.write("   display: block;\n");
      out.write("   margin: 0em 10em 10em 0em;\n");
      out.write("   position: relative;\n");
      out.write("   top: 1em;\n");
      out.write("   right: 5em;\n");
      out.write("   height: 1.3em;\n");
      out.write("   width: 30em;\n");
      out.write("}\n");
      out.write("\n");
      out.write("  </style>\t   \n");
      out.write("\t</head>\n");
      out.write("\n");
      out.write("\t<body>\n");
      out.write("\t   <header>\n");
      out.write("\t      <hgroup>\n");
      out.write("\t      <h1>Hello ");
      out.print( (String)session.getAttribute("username") );
      out.write("</h1> \n");
      out.write("\t      </hgroup>\n");
      out.write("\t   </header>\n");
      out.write("\t    \n");
      out.write("\t\t\t <h2>Find An Item</h2>\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t\t<form id=\"survey\" name=\"survey\"\n");
      out.write("\t\t\t\t\taction=\"UserAccount\"\n");
      out.write("\t\t\t\t\tmethod=\"post\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t<fieldset id=\"searchbar\">\n");
      out.write("\t\t\t\t\t\t<input type=\"search\" name=\"search\" id=\"search\" placeholder=\"Search\"/>\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Go\" />\n");
      out.write("\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</article>\n");
      out.write("\t</body>\n");
      out.write("\t\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
